--320  
  
  SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'AC32' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('AC32') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('AC32')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'AC32' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
    SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'E32' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('E32') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('E32')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'E32' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
    SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'K32' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('K32') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('K32')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'K32' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
--330

  SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'AC33' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('330') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('AC33') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('AC33')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'AC33' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
    SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'E33' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('330') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('E33') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('E33')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'E33' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
    SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'K33' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('330') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('K33') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('K33')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'K33' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
  --737
  
    SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'AC73' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('737') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('AC73') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('AC73')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'AC73' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
      SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'E73' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('737') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('E73') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('E73')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'E73' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
      SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'K73' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('737') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('K73') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('K73')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'K73' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
  --777
  
      SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'AC77' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('777') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('AC77') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('AC77')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'AC77' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
        SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'E77' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('777') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('E77') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('E77')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'E77' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
        SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'K77' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('777') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('K77') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('K77')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'K77' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
  --SU9
  
        SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'ACS9' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('ACS9') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('ACS9')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'ACS9' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
          SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'ES9' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('ES9') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('ES9')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'ES9' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
          SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'KS9' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('KS9') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('KS9')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'KS9' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
  --non fleet specific qualifications
  
            SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'DGS- all fleets' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','737','777','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('DGS') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('DGS')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'DGS' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
              SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'FAL- all fleets' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','737','777','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('FAL') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('FAL')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'FAL' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
              SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'FCHK- all fleets' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','737','777','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('FCHK') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('FCHK')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'FCHK' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
              SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'GO- all fleets' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','737','777','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('GO') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('GO')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'GO' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
              SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'MC- all fleets' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','737','777','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('MC') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('MC')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'MC' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
              SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'MCH- all fleets' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','737','777','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('MCH') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('MCH')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'MCH' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
              SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'MKK- all fleets' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','737','777','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('MKK') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('MKK')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'MKK' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;
  
              SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'PARU- all fleets' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','737','777','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,1), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('PARU') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,-2), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,1)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('PARU')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'PARU' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,1))),'DDMONYY')) 
  ORDER BY STAFF_N;