
M+3 period

SELECT  DISTINCT A.STAFF_NUM  AS STAFF_N, A.PREFERRED_NAME,	A.FIRST_NAME, A.SURNAME, B.RANK_CD,	C.BASE,	P.RSRC_GRP_CD, 'MCH' AS "QUAL"
FROM CREW_RANK_V B,	CREW_BASE_V C, CREW_RSRC_GRP_V P, CREW_V A
WHERE A.STAFF_NUM = B.STAFF_NUM	AND A.STAFF_NUM = C.STAFF_NUM AND A.STAFF_NUM = P.STAFF_NUM
	AND (A.TERM_DT >= TO_DATE(to_char(trunc(add_months(sysdate,3), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.TERM_DT IS NULL)
	AND (A.RETR_DT >= TO_DATE(to_char(trunc(add_months(sysdate,3), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI')	OR A.RETR_DT IS NULL)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,3), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < B.EXP_DT OR B.EXP_DT IS NULL)	AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,3)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > B.EFF_DT)
	AND ((TO_DATE(to_char(trunc(add_months(sysdate,3), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < C.EXP_DT OR C.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,3)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > C.EFF_DT)
	AND A.STAFF_NUM IN (
		SELECT STAFF_NUM FROM CREW_FLEET_V WHERE VALID_IND = 'Y' AND FLEET_CD IN ('320','330','777','737','SU9') 
		AND ((TO_DATE(to_char(trunc(add_months(sysdate,3), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY')))
		OR (TO_DATE(to_char(trunc(last_day(add_months(sysdate,3)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') BETWEEN EFF_DT AND NVL(EXP_DT, TO_DATE('31-DEC-2999', 'DD-MON-YYYY'))))
		GROUP BY STAFF_NUM)
	AND B.RANK_CD IN ('PA','BCA','EC','GM')	AND ((TO_DATE(to_char(trunc(add_months(sysdate,3), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') < P.EXP_DT OR P.EXP_DT IS NULL) AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,3)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') > P.EFF_DT)
	--QUAL
	AND (EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('MCH') AND (NVL(EXPIRY_DTS, TO_DATE('31-DEC-2073', 'DD-MON-YYYY')) 
			BETWEEN TO_DATE(to_char(trunc(add_months(sysdate,0), 'MON'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI') AND TO_DATE(to_char(trunc(last_day(add_months(sysdate,3)),'DD'),'YYYYMMDDHH24MI'), 'YYYYMMDDHH24MI'))) OR  
		NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD IN ('MCH')))
	AND NOT EXISTS (SELECT 1 FROM CREW_QUALIFICATIONS_V Q WHERE Q.STAFF_NUM=A.STAFF_NUM AND QUAL_CD = 'MCH' AND ACTUALS_STATUS IN ('T', 'V')
                AND EXPIRY_DTS > to_char((last_day(add_months(sysdate,3))),'DDMONYY')) 
  ORDER BY STAFF_N;
 